import "./globals.css";
import Providers from "@/components/Providers";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
// import SessionProvider from "@/components/SessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body>
        <main className="flex flex-col overflow-x-hidden">
                  <Providers>
                    <Navbar session={session}/>
                    {children}                  
                  </Providers> 
                <Footer/>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
