import "./globals.css";
import Providers from "@/components/Providers";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SessionWrapper from "@/components/SessionWrapper";
import { getServerSession } from "next-auth";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const session = await getServerSession()
  const response = await fetch("http://localhost:4000/auth/photographer/" + session?.user?.email)
  const photographerRegistered = await response.json();

  return (
    <html lang="en">
      <body>
        <main className="flex flex-col overflow-x-hidden">
          <SessionWrapper session={session}>
            <Providers>
                <Navbar user={session} registeredUser={photographerRegistered?.user}/>
              {children} 
              <Footer/>
            </Providers> 
          </ SessionWrapper>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
